/*
 * FreqTableViewer.java
 *
 * Created on Apr 29, 2011, 2:41:50 PM
 */
package views.snp;

import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 * Holds the Frequency table for viewing ... controls the general UI look and feel.
 * @author rcurtis
 */
public class FreqTableViewer extends javax.swing.JFrame
{
    /**
     * Data object that holds all the tables of values for the total
     * and each population.
     */
    private ArrayList<double[][]> tables;
    /**
     * ArrayList of p-values that tell the significance of the X2 tests
     * for each population.
     */
    private ArrayList<Double> pval;
    /**
     * ArrayList of X2 test statistics that tell the significance of the tests.
     */
    private ArrayList<Double> chiSQ;
    /**
     * The total number of populations in this dataset.
     */
    private int numPops;
    /**
     * The current population that we are looking at. 
     */
    private int curPop;

    public void setVisible()
    {
        this.setVisible(true);
    }

    /** Creates new form FreqTableViewer */
    public FreqTableViewer(ArrayList<double[][]> tables, ArrayList<Double> pval, ArrayList<Double> chiSQ, String traitname)
    {
        initComponents();
        this.pval = pval;
        this.chiSQ = chiSQ;
        this.tables = tables;
        this.curPop = 0;
        this.numPops = tables.size()-1;
        double[][] table = tables.get(0);
        setupUI(table, chiSQ.get(0), pval.get(0));
        if(tables.size() == 1)
        {
            lButton.setEnabled(false);
            rButton.setEnabled(false);
        }
        this.setTitle(traitname);
    }

    private void setupUI(double[][] table, double chiSQ, double pval)
    {
        jPanel1.removeAll();
        FrequencyTable ft = new FrequencyTable(table, chiSQ, pval);
        double[][] expected = calcExpectedTable(table);
        FrequencyTable ft2 = new FrequencyTable(expected, chiSQ, pval);
        this.jPanel1.setLayout(new GridBagLayout());
        GridBagConstraints c = new GridBagConstraints();
        JLabel lab1 = new JLabel("Observed");
        lab1.setFont(new Font("Times", 1, 18));
        c.fill = GridBagConstraints.HORIZONTAL;
        c.gridx = 0;
        c.gridy = 0;
        jPanel1.add(lab1, c);
        c.gridx = 0;
        c.gridy = 1;
        c.gridwidth = 3;
        jPanel1.add(ft, c);
        JLabel lab2 = new JLabel("Expected");
        lab2.setFont(new Font("Times", 1, 18));
        c.gridx = 0;
        c.gridy = 2;
        c.gridwidth = 1;
        jPanel1.add(lab2, c);
        c.gridx = 0;
        c.gridy = 3;
        c.gridwidth = 3;
        jPanel1.add(ft2, c);
        c.gridwidth = 1;
        c.gridx = 0;
        c.gridy = 4;
        this.jPanel1.add(new JLabel("p-value = " + pval), c);
        c.gridy = 5;
        this.jPanel1.add(new JLabel("X2 = " + chiSQ), c);
        jPanel1.updateUI();
        jPanel1.repaint();
        this.repaint();
    }

    private double[][] calcExpectedTable(double[][] table)
    {
        double total = 0.0;
        for (int i = 0; i < table.length; i++)
        {
            for (int j = 0; j < table[0].length; j++)
            {
                total += table[i][j];
            }
        }
        double[][] expected = new double[3][2];
        double perCase = 0.0;
        for (int i = 0; i < 3; i++)
        {
            perCase += table[i][0];
        }
        perCase /= total;
        double perCntr = 1 - perCase;
        for (int i = 0; i < 3; i++)
        {
            double perGen = table[i][0] + table[i][1];
            perGen /= total;
            expected[i][0] = perGen * perCase * total;
            expected[i][1] = perGen * perCntr * total;
        }
        return expected;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        jLabel1.setText("ALL");

        lButton.setText("<");
        lButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lButtonActionPerformed(evt);
            }
        });

        rButton.setText(">");
        rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rButton)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lButton)
                    .addComponent(jLabel1)
                    .addComponent(rButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lButtonActionPerformed
    {//GEN-HEADEREND:event_lButtonActionPerformed
        curPop --;
        if(curPop < 0)
            curPop = numPops;
        setupUI(tables.get(curPop), chiSQ.get(curPop), pval.get(curPop));
        this.jLabel1.setText(curPop == 0 ? "ALL" : curPop + "");
    }//GEN-LAST:event_lButtonActionPerformed

    private void rButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rButtonActionPerformed
    {//GEN-HEADEREND:event_rButtonActionPerformed
        curPop ++;
        if(curPop > numPops)
            curPop = 0;
        setupUI(tables.get(curPop), chiSQ.get(curPop), pval.get(curPop));
        this.jLabel1.setText(curPop == 0 ? "ALL" : curPop + "");

    }//GEN-LAST:event_rButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new FreqTableViewer(null,null, null, null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lButton;
    private javax.swing.JButton rButton;
    // End of variables declaration//GEN-END:variables
}
