package views.snp;

/**
 * This displays a table of values and allows us to switch between
 * populations. 
 *
 * @author RCurtis
 */
public class FrequencyTable extends javax.swing.JPanel
{
    /** Creates new form  */
    public FrequencyTable(double[][] table, double chiSQ, double pval)
    {
        initComponents();
        jTable1.setModel(new FrequencyTableModel(table));
        /*TableColumnModel tcm = jTable1.getColumnModel();
        TableColumn columns = tcm.getColumn(0);
        TableCellRenderer renderer = new ColorCellTableRenderer();
        columns.setCellRenderer(renderer);*/
    }

/*    public void setup(ArrayList<GoItems> items, ArrayList<String> gocats,
            Map<String, Color> goCatColorMap, GoListener listener, int type)
    {
        jTable1.setModel(new GoTableModel(items, gocats, goCatColorMap, type));
        TableColumnModel tcm = jTable1.getColumnModel();
        TableColumn columns = tcm.getColumn(0);
        TableCellRenderer renderer = new ColorCellTableRenderer();
        columns.setCellRenderer(renderer);

    }*/

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
