/*
 * ThreeWayVisualizationSettingsGUI.java
 *
 * Created on Jun 14, 2011, 1:47:36 PM
 */
package views.network.threeway;

import datamodel.GeneTraitAssociation;
import datamodel.ThreeWayVisualizationSettings;
import heatchart.HeatChart;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;
import views.heatmap.HeatChartScale;

/**
 * The visualization settings for the three-way association view are controlled
 * through this layout. It largely acts as a view between the visualization
 * and the user - the user can set settings, etc. 
 * @author rcurtis
 */
public class ThreeWayVisualizationSettingsGUI extends javax.swing.JFrame implements Observer
{
    /**
     * The settings that we are working with
     */
    private ThreeWayVisualizationSettings settings;
    /**
     * A collection of Images that represent the keys for association strengths
     * for gene-snp association in the view.
     */
    private ArrayList<ImagePanel1> charts;
    /**
     * We keep track of where in the image panel list we are so that we can switch
     * between them. 
     */
    private int curIndexCharts = 0;

    /** Creates new form ThreeWayVisualizationSettingsGUI */
    public ThreeWayVisualizationSettingsGUI(ThreeWayVisualizationSettings settings, GeneTraitAssociation gta)
    {
        initComponents();
        this.settings = settings;

        this.numIterationsSpinner.setModel(new SpinnerNumberModel(1000, 100, 5000, 500));
        this.assocForceSpinner.setModel(new SpinnerNumberModel(settings.getSpringLayoutAssociationForceMultiplier(), 0.1, 10, .33));
        this.geneRepulseSpinner.setModel(new SpinnerNumberModel(settings.getSpringLayoutGeneRepulsionFactor(), 1, 200, 2));
        this.traitRepulsSpinner.setModel(new SpinnerNumberModel(settings.getSpringLayoutTraitRepulsionFactor(), 1, 200, 2));
        this.layoutStretchSpinner.setModel(new SpinnerNumberModel(settings.getSpringLayoutStretch(), 0.1, 10, .1));

        this.jPanel3.setLayout(new BorderLayout());
        this.jPanel3.add(new JLabel(new ImageIcon(getClass().getResource("images/GenAMap3WayKey.jpg"))),
                BorderLayout.WEST);


        MyJSlider ms = new MyJSlider(this.associationEdgeSlider, gta.getMaxGTAssocWeight());
        this.associationEdgeSlider.setUI(ms);

        MyJSlider ms2 = new MyJSlider(this.traitEdgeSlider, gta.getMaxTraitEdgeWeight());
        this.traitEdgeSlider.setUI(ms2);

        MyJSlider ms3 = new MyJSlider(this.geneEdgeSlider, gta.getMaxGeneEdgeWeight());
        this.geneEdgeSlider.setUI(ms3);

        this.jPanelForImage.setVisible(false);
        this.chartscaleBtn2.setVisible(false);
        this.chartscaleBtnL.setVisible(false);
        this.chartscaleLab.setVisible(false);
        this.jLabel16.setVisible(false);

        settings.addObserver(this);
        update(null, null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        kklayoutBtn = new javax.swing.JRadioButton();
        forceLayoutBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        variableSpinner1 = new javax.swing.JSpinner();
        variableSpinner2 = new javax.swing.JSpinner();
        traitRepulsSpinner = new javax.swing.JSpinner();
        layoutStretchSpinner = new javax.swing.JSpinner();
        assocForceSpinner = new javax.swing.JSpinner();
        geneRepulseSpinner = new javax.swing.JSpinner();
        numIterationsSpinner = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jPanelForImage = new javax.swing.JPanel();
        chartscaleLab = new javax.swing.JLabel();
        chartscaleBtnL = new javax.swing.JButton();
        chartscaleBtn2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        associationEdgeSlider = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        isShowAssocsCheckBox = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        traitEdgeSlider = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        noAssocNodesCheckBox = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        geneEdgeSlider = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        traitlabelsONbtn = new javax.swing.JRadioButton();
        genelabelsONbtn = new javax.swing.JRadioButton();
        geneedgeLabelsONbtn = new javax.swing.JRadioButton();
        traitEdgeLabelsONbtn = new javax.swing.JRadioButton();
        assocedgeLabelsONbtn = new javax.swing.JRadioButton();
        traitLabelsOffbtn = new javax.swing.JRadioButton();
        geneLabelsOFFbtn = new javax.swing.JRadioButton();
        geneedgeLabelsOFFbtn = new javax.swing.JRadioButton();
        traitEdgeLabelsOFFbtn = new javax.swing.JRadioButton();
        assocedgelabelsOFFbtn = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setTitle("3 WAY VISUALIZATION SETTINGS");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(230, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Layout", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 0, 24))); // NOI18N

        kklayoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(kklayoutBtn);
        kklayoutBtn.setText("KK Layout");
        kklayoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kklayoutBtnActionPerformed(evt);
            }
        });

        forceLayoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(forceLayoutBtn);
        forceLayoutBtn.setText("Force-directed Layout");
        forceLayoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forceLayoutBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Number Iterations");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        variableSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                variableSpinner1StateChanged(evt);
            }
        });

        variableSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                variableSpinner2StateChanged(evt);
            }
        });

        traitRepulsSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                traitRepulsSpinnerStateChanged(evt);
            }
        });

        layoutStretchSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                layoutStretchSpinnerStateChanged(evt);
            }
        });

        assocForceSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                assocForceSpinnerStateChanged(evt);
            }
        });

        geneRepulseSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                geneRepulseSpinnerStateChanged(evt);
            }
        });

        numIterationsSpinner.setToolTipText("The number of update iterations the layout makes to settle on node locations");
        numIterationsSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numIterationsSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(kklayoutBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(forceLayoutBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numIterationsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(variableSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(variableSpinner2)
                            .addComponent(traitRepulsSpinner))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(geneRepulseSpinner))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(assocForceSpinner))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(layoutStretchSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kklayoutBtn)
                    .addComponent(forceLayoutBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numIterationsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(variableSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(layoutStretchSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(variableSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assocForceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(traitRepulsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geneRepulseSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Key", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 0, 24))); // NOI18N

        jPanelForImage.setBackground(new java.awt.Color(230, 255, 255));

        javax.swing.GroupLayout jPanelForImageLayout = new javax.swing.GroupLayout(jPanelForImage);
        jPanelForImage.setLayout(jPanelForImageLayout);
        jPanelForImageLayout.setHorizontalGroup(
            jPanelForImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );
        jPanelForImageLayout.setVerticalGroup(
            jPanelForImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        chartscaleLab.setText("10");

        chartscaleBtnL.setText("<");
        chartscaleBtnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartscaleBtnLActionPerformed(evt);
            }
        });

        chartscaleBtn2.setText(">");
        chartscaleBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartscaleBtn2ActionPerformed(evt);
            }
        });

        jLabel16.setText("SNP assoc key");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanelForImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chartscaleBtnL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chartscaleLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chartscaleBtn2))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanelForImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chartscaleLab)
                    .addComponent(chartscaleBtn2)
                    .addComponent(chartscaleBtnL)
                    .addComponent(jLabel16))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 0, 24))); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(3, 2));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        associationEdgeSlider.setBackground(new java.awt.Color(255, 255, 255));
        associationEdgeSlider.setMajorTickSpacing(20);
        associationEdgeSlider.setMinorTickSpacing(10);
        associationEdgeSlider.setPaintTicks(true);
        associationEdgeSlider.setPreferredSize(new java.awt.Dimension(50, 23));
        associationEdgeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                associationEdgeSliderStateChanged(evt);
            }
        });
        jPanel7.add(associationEdgeSlider);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Association Edges");
        jPanel7.add(jLabel8);

        jPanel4.add(jPanel7);

        isShowAssocsCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        isShowAssocsCheckBox.setText("Show associations");
        isShowAssocsCheckBox.setPreferredSize(new java.awt.Dimension(50, 23));
        isShowAssocsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isShowAssocsCheckBoxActionPerformed(evt);
            }
        });
        jPanel4.add(isShowAssocsCheckBox);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        traitEdgeSlider.setBackground(new java.awt.Color(255, 255, 255));
        traitEdgeSlider.setMajorTickSpacing(20);
        traitEdgeSlider.setMinorTickSpacing(10);
        traitEdgeSlider.setPaintTicks(true);
        traitEdgeSlider.setPreferredSize(new java.awt.Dimension(50, 23));
        traitEdgeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                traitEdgeSliderStateChanged(evt);
            }
        });
        jPanel6.add(traitEdgeSlider);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Trait Edges");
        jPanel6.add(jLabel9);

        jPanel4.add(jPanel6);

        noAssocNodesCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        noAssocNodesCheckBox.setText("Show nodes w/o association");
        noAssocNodesCheckBox.setPreferredSize(new java.awt.Dimension(50, 23));
        noAssocNodesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noAssocNodesCheckBoxActionPerformed(evt);
            }
        });
        jPanel4.add(noAssocNodesCheckBox);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        geneEdgeSlider.setBackground(new java.awt.Color(255, 255, 255));
        geneEdgeSlider.setMajorTickSpacing(20);
        geneEdgeSlider.setMinorTickSpacing(10);
        geneEdgeSlider.setPaintTicks(true);
        geneEdgeSlider.setPreferredSize(new java.awt.Dimension(50, 23));
        geneEdgeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                geneEdgeSliderStateChanged(evt);
            }
        });
        jPanel8.add(geneEdgeSlider);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gene Edges");
        jPanel8.add(jLabel10);

        jPanel4.add(jPanel8);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Info");
        jButton1.setToolTipText("click here for information about the visualization");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visualization", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 0, 24))); // NOI18N

        traitlabelsONbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(traitlabelsONbtn);
        traitlabelsONbtn.setText("ON");
        traitlabelsONbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traitlabelsONbtnActionPerformed(evt);
            }
        });

        genelabelsONbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(genelabelsONbtn);
        genelabelsONbtn.setText("ON");
        genelabelsONbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genelabelsONbtnActionPerformed(evt);
            }
        });

        geneedgeLabelsONbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(geneedgeLabelsONbtn);
        geneedgeLabelsONbtn.setText("ON");
        geneedgeLabelsONbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geneedgeLabelsONbtnActionPerformed(evt);
            }
        });

        traitEdgeLabelsONbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(traitEdgeLabelsONbtn);
        traitEdgeLabelsONbtn.setText("ON");
        traitEdgeLabelsONbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traitEdgeLabelsONbtnActionPerformed(evt);
            }
        });

        assocedgeLabelsONbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(assocedgeLabelsONbtn);
        assocedgeLabelsONbtn.setText("ON");
        assocedgeLabelsONbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assocedgeLabelsONbtnActionPerformed(evt);
            }
        });

        traitLabelsOffbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(traitLabelsOffbtn);
        traitLabelsOffbtn.setText("OFF");
        traitLabelsOffbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traitLabelsOffbtnActionPerformed(evt);
            }
        });

        geneLabelsOFFbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(geneLabelsOFFbtn);
        geneLabelsOFFbtn.setText("OFF");
        geneLabelsOFFbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geneLabelsOFFbtnActionPerformed(evt);
            }
        });

        geneedgeLabelsOFFbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(geneedgeLabelsOFFbtn);
        geneedgeLabelsOFFbtn.setText("OFF");
        geneedgeLabelsOFFbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geneedgeLabelsOFFbtnActionPerformed(evt);
            }
        });

        traitEdgeLabelsOFFbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(traitEdgeLabelsOFFbtn);
        traitEdgeLabelsOFFbtn.setText("OFF");
        traitEdgeLabelsOFFbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traitEdgeLabelsOFFbtnActionPerformed(evt);
            }
        });

        assocedgelabelsOFFbtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(assocedgelabelsOFFbtn);
        assocedgelabelsOFFbtn.setText("OFF");
        assocedgelabelsOFFbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assocedgelabelsOFFbtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Trait Labels");

        jLabel12.setText("Gene Labels");

        jLabel13.setText("Gene Edge Labels");

        jLabel14.setText("Trait Edge Labels");

        jLabel15.setText("Association Edge Labels");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(traitlabelsONbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(traitLabelsOffbtn))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(genelabelsONbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(geneLabelsOFFbtn))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(geneedgeLabelsONbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(geneedgeLabelsOFFbtn)))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(traitEdgeLabelsONbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(traitEdgeLabelsOFFbtn))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(assocedgeLabelsONbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(assocedgelabelsOFFbtn)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(traitlabelsONbtn)
                            .addComponent(traitLabelsOffbtn)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genelabelsONbtn)
                            .addComponent(geneLabelsOFFbtn)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(geneedgeLabelsONbtn)
                            .addComponent(geneedgeLabelsOFFbtn)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(traitEdgeLabelsONbtn)
                            .addComponent(traitEdgeLabelsOFFbtn)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assocedgeLabelsONbtn)
                            .addComponent(assocedgelabelsOFFbtn)
                            .addComponent(jLabel15))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kklayoutBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_kklayoutBtnActionPerformed
    {//GEN-HEADEREND:event_kklayoutBtnActionPerformed
        settings.setToKKLayout();
    }//GEN-LAST:event_kklayoutBtnActionPerformed

    private void forceLayoutBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_forceLayoutBtnActionPerformed
    {//GEN-HEADEREND:event_forceLayoutBtnActionPerformed
        settings.setToFDLayout();
    }//GEN-LAST:event_forceLayoutBtnActionPerformed

    private void numIterationsSpinnerStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_numIterationsSpinnerStateChanged
    {//GEN-HEADEREND:event_numIterationsSpinnerStateChanged
        settings.setNumberLayoutUpdateIterations((Integer) this.numIterationsSpinner.getValue());
    }//GEN-LAST:event_numIterationsSpinnerStateChanged

    private void variableSpinner1StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_variableSpinner1StateChanged
    {//GEN-HEADEREND:event_variableSpinner1StateChanged
        if (settings.getIsKKLayout())
        {
            settings.setKKLayoutDisconnectedMultiplier((Double) this.variableSpinner1.getValue());
        }
        else
        {
            settings.setSpringLayoutRepulsionRange((Integer) this.variableSpinner1.getValue());
        }
    }//GEN-LAST:event_variableSpinner1StateChanged

    private void variableSpinner2StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_variableSpinner2StateChanged
    {//GEN-HEADEREND:event_variableSpinner2StateChanged
        if (settings.getIsKKLayout())
        {
            settings.setKKLayoutLengthFactor((Double) this.variableSpinner2.getValue());
        }
        else
        {
            settings.setSpringLayoutCorrelationForceMultiplier((Double) this.variableSpinner2.getValue());
        }
    }//GEN-LAST:event_variableSpinner2StateChanged

    private void traitRepulsSpinnerStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_traitRepulsSpinnerStateChanged
    {//GEN-HEADEREND:event_traitRepulsSpinnerStateChanged
        settings.setSpringLayoutTraitRepulsionFactor((Double) this.traitRepulsSpinner.getValue());
    }//GEN-LAST:event_traitRepulsSpinnerStateChanged

    private void layoutStretchSpinnerStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_layoutStretchSpinnerStateChanged
    {//GEN-HEADEREND:event_layoutStretchSpinnerStateChanged
        settings.setSpringLayoutStretch((Double) this.layoutStretchSpinner.getValue());
    }//GEN-LAST:event_layoutStretchSpinnerStateChanged

    private void assocForceSpinnerStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_assocForceSpinnerStateChanged
    {//GEN-HEADEREND:event_assocForceSpinnerStateChanged
        settings.setSpringLayoutAssociationForceMultiplier((Double) this.assocForceSpinner.getValue());
    }//GEN-LAST:event_assocForceSpinnerStateChanged

    private void geneRepulseSpinnerStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_geneRepulseSpinnerStateChanged
    {//GEN-HEADEREND:event_geneRepulseSpinnerStateChanged
        settings.setSpringLayoutGeneRepulsionFactor((Double) this.geneRepulseSpinner.getValue());
    }//GEN-LAST:event_geneRepulseSpinnerStateChanged

    private void isShowAssocsCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_isShowAssocsCheckBoxActionPerformed
    {//GEN-HEADEREND:event_isShowAssocsCheckBoxActionPerformed
        noAssocNodesCheckBox.setSelected(true);
        settings.setIsShowAssociationEdges(isShowAssocsCheckBox.isSelected());
    }//GEN-LAST:event_isShowAssocsCheckBoxActionPerformed

    private void noAssocNodesCheckBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_noAssocNodesCheckBoxActionPerformed
    {//GEN-HEADEREND:event_noAssocNodesCheckBoxActionPerformed
        settings.setIsShowUnconnectedNodes(noAssocNodesCheckBox.isSelected());
    }//GEN-LAST:event_noAssocNodesCheckBoxActionPerformed

    private void associationEdgeSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_associationEdgeSliderStateChanged
    {//GEN-HEADEREND:event_associationEdgeSliderStateChanged
        settings.setAssocEdgeThreshold(((MyJSlider) associationEdgeSlider.getUI()).getValue());
    }//GEN-LAST:event_associationEdgeSliderStateChanged

    private void traitEdgeSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_traitEdgeSliderStateChanged
    {//GEN-HEADEREND:event_traitEdgeSliderStateChanged
        settings.setTraitEdgeThreshold(((MyJSlider) traitEdgeSlider.getUI()).getValue());
    }//GEN-LAST:event_traitEdgeSliderStateChanged

    private void geneEdgeSliderStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_geneEdgeSliderStateChanged
    {//GEN-HEADEREND:event_geneEdgeSliderStateChanged
        settings.setGeneEdgeThreshold(((MyJSlider) geneEdgeSlider.getUI()).getValue());
    }//GEN-LAST:event_geneEdgeSliderStateChanged

    private void traitlabelsONbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_traitlabelsONbtnActionPerformed
    {//GEN-HEADEREND:event_traitlabelsONbtnActionPerformed
        if (traitlabelsONbtn.isSelected())
        {
            settings.setIsShowTraitLabs(true);
        }
    }//GEN-LAST:event_traitlabelsONbtnActionPerformed

    private void traitLabelsOffbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_traitLabelsOffbtnActionPerformed
    {//GEN-HEADEREND:event_traitLabelsOffbtnActionPerformed
        if (traitLabelsOffbtn.isSelected())
        {
            settings.setIsShowTraitLabs(false);
        }
    }//GEN-LAST:event_traitLabelsOffbtnActionPerformed

    private void genelabelsONbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_genelabelsONbtnActionPerformed
    {//GEN-HEADEREND:event_genelabelsONbtnActionPerformed
        if (this.genelabelsONbtn.isSelected())
        {
            settings.setIsShowGeneLabs(true);
        }
    }//GEN-LAST:event_genelabelsONbtnActionPerformed

    private void geneLabelsOFFbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_geneLabelsOFFbtnActionPerformed
    {//GEN-HEADEREND:event_geneLabelsOFFbtnActionPerformed
        if (this.geneLabelsOFFbtn.isSelected())
        {
            settings.setIsShowGeneLabs(false);
        }
    }//GEN-LAST:event_geneLabelsOFFbtnActionPerformed

    private void geneedgeLabelsONbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_geneedgeLabelsONbtnActionPerformed
    {//GEN-HEADEREND:event_geneedgeLabelsONbtnActionPerformed
        if (this.geneedgeLabelsONbtn.isSelected())
        {
            settings.setIsShowGeneEdgeLabs(true);
        }
    }//GEN-LAST:event_geneedgeLabelsONbtnActionPerformed

    private void geneedgeLabelsOFFbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_geneedgeLabelsOFFbtnActionPerformed
    {//GEN-HEADEREND:event_geneedgeLabelsOFFbtnActionPerformed
        if (this.geneedgeLabelsOFFbtn.isSelected())
        {
            settings.setIsShowGeneEdgeLabs(false);
        }
    }//GEN-LAST:event_geneedgeLabelsOFFbtnActionPerformed

    private void traitEdgeLabelsONbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_traitEdgeLabelsONbtnActionPerformed
    {//GEN-HEADEREND:event_traitEdgeLabelsONbtnActionPerformed
        if (this.traitEdgeLabelsONbtn.isSelected())
        {
            settings.setIsShowTraitEdgeLabs(true);
        }
    }//GEN-LAST:event_traitEdgeLabelsONbtnActionPerformed

    private void traitEdgeLabelsOFFbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_traitEdgeLabelsOFFbtnActionPerformed
    {//GEN-HEADEREND:event_traitEdgeLabelsOFFbtnActionPerformed
        if (this.traitEdgeLabelsOFFbtn.isSelected())
        {
            settings.setIsShowTraitEdgeLabs(false);
        }
    }//GEN-LAST:event_traitEdgeLabelsOFFbtnActionPerformed

    private void assocedgeLabelsONbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_assocedgeLabelsONbtnActionPerformed
    {//GEN-HEADEREND:event_assocedgeLabelsONbtnActionPerformed
        if (this.assocedgeLabelsONbtn.isSelected())
        {
            settings.setIsShowAssocEdgeLabs(true);
        }
    }//GEN-LAST:event_assocedgeLabelsONbtnActionPerformed

    private void assocedgelabelsOFFbtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_assocedgelabelsOFFbtnActionPerformed
    {//GEN-HEADEREND:event_assocedgelabelsOFFbtnActionPerformed
        if (this.assocedgelabelsOFFbtn.isSelected())
        {
            settings.setIsShowAssocEdgeLabs(false);
        }
    }//GEN-LAST:event_assocedgelabelsOFFbtnActionPerformed

    private void chartscaleBtn2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chartscaleBtn2ActionPerformed
    {//GEN-HEADEREND:event_chartscaleBtn2ActionPerformed
        this.curIndexCharts++;
        if (this.curIndexCharts >= this.charts.size())
        {
            curIndexCharts = 0;
        }

        JLabel lab = new JLabel();
        lab.setIcon(new ImageIcon(charts.get(this.curIndexCharts).scaleImage));
        this.jPanelForImage.setLayout(new BorderLayout());
        this.jPanelForImage.removeAll();
        this.jPanelForImage.add(lab, BorderLayout.CENTER);
        this.jPanelForImage.repaint();
        this.jPanelForImage.updateUI();

        this.chartscaleLab.setText(charts.get(this.curIndexCharts).label);
    }//GEN-LAST:event_chartscaleBtn2ActionPerformed

    private void chartscaleBtnLActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chartscaleBtnLActionPerformed
    {//GEN-HEADEREND:event_chartscaleBtnLActionPerformed
        this.curIndexCharts--;
        if (this.curIndexCharts < 0)
        {
            curIndexCharts = this.charts.size() - 1;
        }

        JLabel lab = new JLabel();
        lab.setIcon(new ImageIcon(charts.get(this.curIndexCharts).scaleImage));
        this.jPanelForImage.setLayout(new BorderLayout());
        this.jPanelForImage.removeAll();
        this.jPanelForImage.add(lab, BorderLayout.CENTER);
        this.jPanelForImage.repaint();
        this.jPanelForImage.updateUI();

        this.chartscaleLab.setText(charts.get(this.curIndexCharts).label);
    }//GEN-LAST:event_chartscaleBtnLActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Please be aware that GenAMap 3-way association algorithms\n" +
                "use a two-step process to find associations, thus the edges from SNPs to genes\n" +
                "and the edges from genes to traits may or may not be related.");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner assocForceSpinner;
    private javax.swing.JRadioButton assocedgeLabelsONbtn;
    private javax.swing.JRadioButton assocedgelabelsOFFbtn;
    private javax.swing.JSlider associationEdgeSlider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton chartscaleBtn2;
    private javax.swing.JButton chartscaleBtnL;
    private javax.swing.JLabel chartscaleLab;
    private javax.swing.JRadioButton forceLayoutBtn;
    private javax.swing.JSlider geneEdgeSlider;
    private javax.swing.JRadioButton geneLabelsOFFbtn;
    private javax.swing.JSpinner geneRepulseSpinner;
    private javax.swing.JRadioButton geneedgeLabelsOFFbtn;
    private javax.swing.JRadioButton geneedgeLabelsONbtn;
    private javax.swing.JRadioButton genelabelsONbtn;
    private javax.swing.JCheckBox isShowAssocsCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelForImage;
    private javax.swing.JRadioButton kklayoutBtn;
    private javax.swing.JSpinner layoutStretchSpinner;
    private javax.swing.JCheckBox noAssocNodesCheckBox;
    private javax.swing.JSpinner numIterationsSpinner;
    private javax.swing.JRadioButton traitEdgeLabelsOFFbtn;
    private javax.swing.JRadioButton traitEdgeLabelsONbtn;
    private javax.swing.JSlider traitEdgeSlider;
    private javax.swing.JRadioButton traitLabelsOffbtn;
    private javax.swing.JSpinner traitRepulsSpinner;
    private javax.swing.JRadioButton traitlabelsONbtn;
    private javax.swing.JSpinner variableSpinner1;
    private javax.swing.JSpinner variableSpinner2;
    // End of variables declaration//GEN-END:variables

    /**
     * Updates the GUI to reflect the current state of the settings that
     * are being used. 
     */
    public void update(Observable o, Object arg)
    {
        if (this.settings.getIsKKLayout())
        {
            this.kklayoutBtn.setSelected(true);
            this.jLabel2.setText("Disconnected Multiplier");
            this.jLabel3.setText(("Length Factor"));
            this.jLabel4.setVisible(false);
            this.jLabel5.setVisible(false);
            this.jLabel6.setVisible(false);
            this.jLabel7.setVisible(false);
            this.traitRepulsSpinner.setVisible(false);
            this.geneRepulseSpinner.setVisible(false);
            this.assocForceSpinner.setVisible(false);
            this.layoutStretchSpinner.setVisible(false);
            this.variableSpinner1.setModel(new SpinnerNumberModel(settings.getKKLayoutDisconnectedMultiplier(), .01, 10, .1));
            this.variableSpinner2.setModel(new SpinnerNumberModel(settings.getKKLayoutLengthFactor(), .1, 5, .1));
        }
        else
        {
            this.forceLayoutBtn.setSelected(true);
            this.jLabel4.setVisible(true);
            this.jLabel5.setVisible(true);
            this.jLabel6.setVisible(true);
            this.jLabel7.setVisible(true);
            this.jLabel2.setText("Repulsion Range");
            this.jLabel5.setText("Layout Stretch");
            this.jLabel3.setText("Corr. Force");
            this.jLabel6.setText("Assoc. Force");
            this.jLabel4.setText("Trait Repuls.");
            this.jLabel7.setText("Gene Repuls.");
            this.traitRepulsSpinner.setVisible(true);
            this.traitRepulsSpinner.setValue(settings.getSpringLayoutTraitRepulsionFactor());
            this.geneRepulseSpinner.setVisible(true);
            this.geneRepulseSpinner.setValue(settings.getSpringLayoutGeneRepulsionFactor());
            this.assocForceSpinner.setVisible(true);
            this.assocForceSpinner.setValue(settings.getSpringLayoutAssociationForceMultiplier());
            this.layoutStretchSpinner.setVisible(true);
            this.layoutStretchSpinner.setValue(settings.getSpringLayoutStretch());
            this.variableSpinner1.setModel(new SpinnerNumberModel(settings.getSpringLayoutRepulsionRange(), 1, 500, 5));
            this.variableSpinner2.setModel(new SpinnerNumberModel(settings.getSpringLayoutCorrelationForceMultiplier(), 0.1, 10, 0.33));
        }
        this.numIterationsSpinner.setValue(settings.getNumberLayoutUpdateIterations());
        this.isShowAssocsCheckBox.setSelected(settings.getIsShowAssociationEdges());
        this.noAssocNodesCheckBox.setSelected(settings.getIsShowUnconnectedNodes());
        ((MyJSlider) this.associationEdgeSlider.getUI()).setValue(settings.getAssocEdgeThreshold());
        ((MyJSlider) this.traitEdgeSlider.getUI()).setValue(settings.getTraitEdgeThreshold());
        ((MyJSlider) this.geneEdgeSlider.getUI()).setValue(settings.getGeneEdgeThreshold());
        this.associationEdgeSlider.setEnabled(this.isShowAssocsCheckBox.isSelected());
        this.traitlabelsONbtn.setSelected(settings.getIsShowTraitLabs());
        this.traitLabelsOffbtn.setSelected(!settings.getIsShowTraitLabs());
        this.genelabelsONbtn.setSelected(settings.getIsShowGeneLabs());
        this.geneLabelsOFFbtn.setSelected(!settings.getIsShowGeneLabs());
        this.traitEdgeLabelsONbtn.setSelected(settings.getIsShowTraitEdgeLabs());
        this.traitEdgeLabelsOFFbtn.setSelected(!settings.getIsShowTraitEdgeLabs());
        this.geneedgeLabelsONbtn.setSelected(settings.getIsShowGeneEdgeLabs());
        this.geneedgeLabelsOFFbtn.setSelected(!settings.getIsShowGeneEdgeLabs());
        this.assocedgeLabelsONbtn.setSelected(settings.getIsShowAssocEdgeLabs());
        this.assocedgelabelsOFFbtn.setSelected(!settings.getIsShowAssocEdgeLabs());

    }

    public void showChartKeys(ArrayList<ImagePanel1> charts)
    {
        this.charts = charts;
        this.jPanelForImage.setVisible(true);
        this.chartscaleBtn2.setVisible(true);
        this.chartscaleBtnL.setVisible(true);
        this.chartscaleLab.setVisible(true);
        this.jLabel16.setVisible(true);
        curIndexCharts = 0;

        JLabel lab = new JLabel();
        lab.setIcon(new ImageIcon(charts.get(this.curIndexCharts).scaleImage));
        this.jPanelForImage.setLayout(new BorderLayout());
        this.jPanelForImage.removeAll();
        this.jPanelForImage.add(lab, BorderLayout.CENTER);
        this.jPanelForImage.repaint();
        this.jPanelForImage.updateUI();

        this.chartscaleLab.setText(charts.get(this.curIndexCharts).label);
    }
    /**
     * When we are showing genetic association, the key panel will display a
     * color bar indicating the strength of associations between the genes and
     * genome. This is done through this image panel.
     *
     * We couldn't get this to work as expected, and so this class is currently
     * used to store the image and label to be displayed. The GUI keeps
     * track of a bunch of these when appropriate.
     */
    public static class ImagePanel1 extends JPanel
    {
        public Image scaleImage;
        public String label;
        public Color c;

        @Override
        public void paintComponent(Graphics g)
        {
            super.paintComponent(g);
            if (scaleImage != null)
            {
                //draw image with some x and y displacement
                g.drawImage(scaleImage, 0, 0, this);
            }
        }
    }
}
