/*
 * TestComparisonFrame.java
 *
 * Created on May 25, 2011, 2:59:19 PM
 */
package views.snp.comparison;

import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import views.snp.ManhattanPlotsManager;

/**
 * In a situation with multiple tests and multiple populations or traits, we
 * will want to be able to get a quick summary of what the associations are.
 *
 * Through the TestComparisonFrame, we are able to understand just what is
 * going on between these associations. Here, we create our own data model
 * from the associations themselves, and then we fill in the results and
 * allow the user to filter based on their own dynamic query preferences. 
 * @author rcurtis
 */
public class TestComparisonFrame extends javax.swing.JFrame
{
    /**
     * datamodel that contains the data that we will be using for all of our
     * dynamic query stuff.
     */
    private DataModel model;
    /**
     * All of the boxes for tests on the GUI
     */
    private ArrayList<JCheckBox> boxes;
    /**
     * All of the significance fields on the GUI
     */
    private ArrayList<JTextField> fields;
    /**
     * All of the radio buttons of which associations to display
     */
    private ArrayList<JRadioButton> buttons;
    /**
     * The array list of radio buttons belonging to categories
     */
    private ArrayList<JRadioButton> cats;

    /** Creates new form TestComparisonFrame */
    public TestComparisonFrame(ManhattanPlotsManager mpm)
    {
        super();
        initComponents();
        model = new DataModel(mpm);

        boxes = new ArrayList<JCheckBox>();
        boxes.add(testLab1);
        boxes.add(testLab2);
        boxes.add(testLab3);
        boxes.add(testLab4);
        boxes.add(testLab5);
        boxes.add(testLab6);
        boxes.add(testLab7);
        boxes.add(testLab8);
        boxes.add(testLab9);
        boxes.add(testLab10);

        fields = new ArrayList<JTextField>();
        fields.add(sigLev1);
        fields.add(sigLev2);
        fields.add(sigLev3);
        fields.add(sigLev4);
        fields.add(sigLev5);
        fields.add(sigLev6);
        fields.add(sigLev7);
        fields.add(sigLev8);
        fields.add(sigLev9);
        fields.add(sigLev10);

        buttons = new ArrayList<JRadioButton>();
        buttons.add(testRadButton1);
        buttons.add(testRadButton2);
        buttons.add(testRadButton3);
        buttons.add(testRadButton4);
        buttons.add(testRadButton5);
        buttons.add(testRadButton6);
        buttons.add(testRadButton7);
        buttons.add(testRadButton8);
        buttons.add(testRadButton9);
        buttons.add(testRadButton10);

        cats = new ArrayList<JRadioButton>();
        cats.add(this.catRadBtn1);
        cats.add(this.catRadBtn2);
        cats.add(this.catRadBtn3);
        cats.add(this.catRadBtn4);
        cats.add(this.catRadBtn5);
        cats.add(this.catRadBtn6);
        cats.add(this.catRadBtn7);
        cats.add(this.catRadBtn8);
        cats.add(this.catRadBtn9);
        cats.add(this.catRadBtn10);

        this.jLabel4.setVisible(false);
        this.numBases100000Btn.setVisible(false);
        this.numBases10000Btn.setVisible(false);
        this.numBases1000Btn.setVisible(false);
        this.numBases100Btn.setVisible(false);
        this.numBases10Btn.setVisible(false);

        for (int i = 0; i < 10; i++)
        {
            boxes.get(i).setSelected(true);
            boxes.get(i).setVisible(false);
            fields.get(i).setVisible(false);
            buttons.get(i).setVisible(false);
        }

        this.numBases10Btn.setSelected(true);

        updateUI(1);
        updateUI(2);

        this.resultsTable.setModel(model);
        this.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsTable = new javax.swing.JTable();
        testLab1 = new javax.swing.JCheckBox();
        testLab2 = new javax.swing.JCheckBox();
        testLab3 = new javax.swing.JCheckBox();
        testLab4 = new javax.swing.JCheckBox();
        testLab5 = new javax.swing.JCheckBox();
        testLab6 = new javax.swing.JCheckBox();
        testLab7 = new javax.swing.JCheckBox();
        testLab8 = new javax.swing.JCheckBox();
        testLab9 = new javax.swing.JCheckBox();
        testLab10 = new javax.swing.JCheckBox();
        sigLev1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sigLev2 = new javax.swing.JTextField();
        sigLev4 = new javax.swing.JTextField();
        sigLev3 = new javax.swing.JTextField();
        sigLev6 = new javax.swing.JTextField();
        sigLev5 = new javax.swing.JTextField();
        sigLev8 = new javax.swing.JTextField();
        sigLev7 = new javax.swing.JTextField();
        sigLev9 = new javax.swing.JTextField();
        sigLev10 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultsTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        numBases10Btn = new javax.swing.JRadioButton();
        numBases100Btn = new javax.swing.JRadioButton();
        numBases1000Btn = new javax.swing.JRadioButton();
        numBases10000Btn = new javax.swing.JRadioButton();
        numBases100000Btn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        testRadButton2 = new javax.swing.JRadioButton();
        testRadButton3 = new javax.swing.JRadioButton();
        testRadButton6 = new javax.swing.JRadioButton();
        testRadButton1 = new javax.swing.JRadioButton();
        testRadButton9 = new javax.swing.JRadioButton();
        testRadButton7 = new javax.swing.JRadioButton();
        testRadButton5 = new javax.swing.JRadioButton();
        testRadButton8 = new javax.swing.JRadioButton();
        testRadButton4 = new javax.swing.JRadioButton();
        testRadButton10 = new javax.swing.JRadioButton();
        catRadBtn1 = new javax.swing.JRadioButton();
        catRadBtn2 = new javax.swing.JRadioButton();
        catRadBtn3 = new javax.swing.JRadioButton();
        catRadBtn5 = new javax.swing.JRadioButton();
        catRadBtn4 = new javax.swing.JRadioButton();
        catRadBtn9 = new javax.swing.JRadioButton();
        catRadBtn6 = new javax.swing.JRadioButton();
        catRadBtn7 = new javax.swing.JRadioButton();
        catRadBtn8 = new javax.swing.JRadioButton();
        catRadBtn10 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        resultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(resultsTable);

        testLab1.setText("jCheckBox4");
        testLab1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        testLab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testLab1ActionPerformed(evt);
            }
        });

        testLab2.setText("jCheckBox1");
        testLab2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        testLab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testLab2ActionPerformed(evt);
            }
        });

        testLab3.setText("jCheckBox2");
        testLab3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        testLab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testLab3ActionPerformed(evt);
            }
        });

        testLab4.setText("jCheckBox3");
        testLab4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        testLab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testLab4ActionPerformed(evt);
            }
        });

        testLab5.setText("jCheckBox5");
        testLab5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        testLab5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testLab5ActionPerformed(evt);
            }
        });

        testLab6.setText("jCheckBox6");
        testLab6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        testLab6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testLab6ActionPerformed(evt);
            }
        });

        testLab7.setText("jCheckBox7");
        testLab7.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        testLab7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testLab7ActionPerformed(evt);
            }
        });

        testLab8.setText("jCheckBox8");
        testLab8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        testLab8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testLab8ActionPerformed(evt);
            }
        });

        testLab9.setText("jCheckBox9");
        testLab9.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        testLab9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testLab9ActionPerformed(evt);
            }
        });

        testLab10.setText("jCheckBox10");
        testLab10.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        testLab10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testLab10ActionPerformed(evt);
            }
        });

        sigLev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigLev1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Association Analysis Comparisons");

        sigLev2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigLev2ActionPerformed(evt);
            }
        });

        sigLev4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigLev4ActionPerformed(evt);
            }
        });

        sigLev3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigLev3ActionPerformed(evt);
            }
        });

        sigLev6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigLev6ActionPerformed(evt);
            }
        });

        sigLev5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigLev5ActionPerformed(evt);
            }
        });

        sigLev8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigLev8ActionPerformed(evt);
            }
        });

        sigLev7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigLev7ActionPerformed(evt);
            }
        });

        sigLev9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigLev9ActionPerformed(evt);
            }
        });

        sigLev10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigLev10ActionPerformed(evt);
            }
        });

        jLabel2.setText("Significance Level");

        resultsTextArea.setColumns(20);
        resultsTextArea.setEditable(false);
        resultsTextArea.setRows(5);
        jScrollPane2.setViewportView(resultsTextArea);

        jLabel3.setText("Test");

        buttonGroup1.add(numBases10Btn);
        numBases10Btn.setText("10 bases");
        numBases10Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numBases10BtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(numBases100Btn);
        numBases100Btn.setText("100 bases");
        numBases100Btn.setToolTipText("");
        numBases100Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numBases100BtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(numBases1000Btn);
        numBases1000Btn.setText("1000 bases");
        numBases1000Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numBases1000BtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(numBases10000Btn);
        numBases10000Btn.setText("10 kb");
        numBases10000Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numBases10000BtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(numBases100000Btn);
        numBases100000Btn.setText("100 kb");
        numBases100000Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numBases100000BtnActionPerformed(evt);
            }
        });

        jLabel4.setText("<html>Distance for <i>cis</i></html>");

        buttonGroup2.add(testRadButton2);
        testRadButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRadButton2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(testRadButton3);
        testRadButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRadButton3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(testRadButton6);
        testRadButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRadButton6ActionPerformed(evt);
            }
        });

        buttonGroup2.add(testRadButton1);
        testRadButton1.setSelected(true);
        testRadButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        testRadButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRadButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(testRadButton9);
        testRadButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRadButton9ActionPerformed(evt);
            }
        });

        buttonGroup2.add(testRadButton7);
        testRadButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRadButton7ActionPerformed(evt);
            }
        });

        buttonGroup2.add(testRadButton5);
        testRadButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRadButton5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(testRadButton8);
        testRadButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRadButton8ActionPerformed(evt);
            }
        });

        buttonGroup2.add(testRadButton4);
        testRadButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRadButton4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(testRadButton10);
        testRadButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRadButton10ActionPerformed(evt);
            }
        });

        buttonGroup2.add(catRadBtn1);
        catRadBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadBtn1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(catRadBtn2);
        catRadBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadBtn2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(catRadBtn3);
        catRadBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadBtn3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(catRadBtn5);
        catRadBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadBtn5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(catRadBtn4);
        catRadBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadBtn4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(catRadBtn9);
        catRadBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadBtn9ActionPerformed(evt);
            }
        });

        buttonGroup2.add(catRadBtn6);
        catRadBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadBtn6ActionPerformed(evt);
            }
        });

        buttonGroup2.add(catRadBtn7);
        catRadBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadBtn7ActionPerformed(evt);
            }
        });

        buttonGroup2.add(catRadBtn8);
        catRadBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadBtn8ActionPerformed(evt);
            }
        });

        buttonGroup2.add(catRadBtn10);
        catRadBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catRadBtn10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catRadBtn1)
                            .addComponent(catRadBtn2)
                            .addComponent(catRadBtn3)
                            .addComponent(catRadBtn4)
                            .addComponent(catRadBtn5))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(testRadButton1)
                            .addComponent(testRadButton2)
                            .addComponent(testRadButton3)
                            .addComponent(testRadButton4)
                            .addComponent(testRadButton5)
                            .addComponent(testRadButton9)
                            .addComponent(testRadButton10)
                            .addComponent(testRadButton6)
                            .addComponent(testRadButton7)
                            .addComponent(testRadButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(catRadBtn10)
                        .addComponent(catRadBtn9)
                        .addComponent(catRadBtn8)
                        .addComponent(catRadBtn7)
                        .addComponent(catRadBtn6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testLab10)
                            .addComponent(testLab9)
                            .addComponent(testLab8)
                            .addComponent(testLab7)
                            .addComponent(testLab6)
                            .addComponent(testLab5)
                            .addComponent(testLab4)
                            .addComponent(testLab2)
                            .addComponent(testLab3)))
                    .addComponent(jLabel3)
                    .addComponent(testLab1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(sigLev2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigLev3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigLev4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigLev1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigLev5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigLev6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigLev7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigLev8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigLev9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigLev10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(numBases100Btn)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(numBases10Btn)
                                .addGap(81, 81, 81)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numBases10000Btn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numBases1000Btn)
                                .addGap(46, 46, 46)
                                .addComponent(numBases100000Btn)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(515, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sigLev1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(testLab1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(testLab2)
                                    .addComponent(sigLev2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sigLev3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(testLab3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(testLab4)
                                    .addComponent(sigLev4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(testLab5)
                                    .addComponent(sigLev5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(testLab6)
                                    .addComponent(sigLev6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(testLab7)
                                    .addComponent(sigLev7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(testLab8)
                                    .addComponent(sigLev8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(testLab9)
                                    .addComponent(sigLev9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(testLab10)
                                    .addComponent(sigLev10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(testRadButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(testRadButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(testRadButton3)
                                .addGap(7, 7, 7)
                                .addComponent(testRadButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(testRadButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(testRadButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(testRadButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(testRadButton8)
                                .addGap(10, 10, 10)
                                .addComponent(testRadButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(testRadButton10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(catRadBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(catRadBtn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(catRadBtn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(catRadBtn4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(catRadBtn5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(catRadBtn6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(catRadBtn7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(catRadBtn8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(catRadBtn9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(catRadBtn10)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(numBases10Btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numBases100Btn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numBases1000Btn)
                                    .addComponent(numBases100000Btn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numBases10000Btn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testLab1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testLab1ActionPerformed
    {//GEN-HEADEREND:event_testLab1ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_testLab1ActionPerformed

    private void testLab2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testLab2ActionPerformed
    {//GEN-HEADEREND:event_testLab2ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_testLab2ActionPerformed

    private void testLab4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testLab4ActionPerformed
    {//GEN-HEADEREND:event_testLab4ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_testLab4ActionPerformed

    private void testLab5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testLab5ActionPerformed
    {//GEN-HEADEREND:event_testLab5ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_testLab5ActionPerformed

    private void testLab6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testLab6ActionPerformed
    {//GEN-HEADEREND:event_testLab6ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_testLab6ActionPerformed

    private void testLab7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testLab7ActionPerformed
    {//GEN-HEADEREND:event_testLab7ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_testLab7ActionPerformed

    private void testLab8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testLab8ActionPerformed
    {//GEN-HEADEREND:event_testLab8ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_testLab8ActionPerformed

    private void testLab9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testLab9ActionPerformed
    {//GEN-HEADEREND:event_testLab9ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_testLab9ActionPerformed

    private void testLab10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testLab10ActionPerformed
    {//GEN-HEADEREND:event_testLab10ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_testLab10ActionPerformed

    private void sigLev1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sigLev1ActionPerformed
    {//GEN-HEADEREND:event_sigLev1ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_sigLev1ActionPerformed

    private void sigLev2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sigLev2ActionPerformed
    {//GEN-HEADEREND:event_sigLev2ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_sigLev2ActionPerformed

    private void sigLev3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sigLev3ActionPerformed
    {//GEN-HEADEREND:event_sigLev3ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_sigLev3ActionPerformed

    private void sigLev4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sigLev4ActionPerformed
    {//GEN-HEADEREND:event_sigLev4ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_sigLev4ActionPerformed

    private void sigLev5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sigLev5ActionPerformed
    {//GEN-HEADEREND:event_sigLev5ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_sigLev5ActionPerformed

    private void sigLev6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sigLev6ActionPerformed
    {//GEN-HEADEREND:event_sigLev6ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_sigLev6ActionPerformed

    private void sigLev7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sigLev7ActionPerformed
    {//GEN-HEADEREND:event_sigLev7ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_sigLev7ActionPerformed

    private void sigLev8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sigLev8ActionPerformed
    {//GEN-HEADEREND:event_sigLev8ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_sigLev8ActionPerformed

    private void sigLev9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sigLev9ActionPerformed
    {//GEN-HEADEREND:event_sigLev9ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_sigLev9ActionPerformed

    private void sigLev10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sigLev10ActionPerformed
    {//GEN-HEADEREND:event_sigLev10ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_sigLev10ActionPerformed

    private void numBases10BtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numBases10BtnActionPerformed
    {//GEN-HEADEREND:event_numBases10BtnActionPerformed
        updateUI(1);
    }//GEN-LAST:event_numBases10BtnActionPerformed

    private void numBases100BtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numBases100BtnActionPerformed
    {//GEN-HEADEREND:event_numBases100BtnActionPerformed
        updateUI(1);
    }//GEN-LAST:event_numBases100BtnActionPerformed

    private void numBases1000BtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numBases1000BtnActionPerformed
    {//GEN-HEADEREND:event_numBases1000BtnActionPerformed
        updateUI(1);
    }//GEN-LAST:event_numBases1000BtnActionPerformed

    private void numBases10000BtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numBases10000BtnActionPerformed
    {//GEN-HEADEREND:event_numBases10000BtnActionPerformed
        updateUI(1);
    }//GEN-LAST:event_numBases10000BtnActionPerformed

    private void numBases100000BtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numBases100000BtnActionPerformed
    {//GEN-HEADEREND:event_numBases100000BtnActionPerformed
        updateUI(1);
    }//GEN-LAST:event_numBases100000BtnActionPerformed

    private void testLab3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testLab3ActionPerformed
    {//GEN-HEADEREND:event_testLab3ActionPerformed
        updateUI(2);
}//GEN-LAST:event_testLab3ActionPerformed

    private void testRadButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testRadButton1ActionPerformed
    {//GEN-HEADEREND:event_testRadButton1ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_testRadButton1ActionPerformed

    private void testRadButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testRadButton2ActionPerformed
    {//GEN-HEADEREND:event_testRadButton2ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_testRadButton2ActionPerformed

    private void testRadButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testRadButton3ActionPerformed
    {//GEN-HEADEREND:event_testRadButton3ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_testRadButton3ActionPerformed

    private void testRadButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testRadButton4ActionPerformed
    {//GEN-HEADEREND:event_testRadButton4ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_testRadButton4ActionPerformed

    private void testRadButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testRadButton5ActionPerformed
    {//GEN-HEADEREND:event_testRadButton5ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_testRadButton5ActionPerformed

    private void testRadButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testRadButton6ActionPerformed
    {//GEN-HEADEREND:event_testRadButton6ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_testRadButton6ActionPerformed

    private void testRadButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testRadButton7ActionPerformed
    {//GEN-HEADEREND:event_testRadButton7ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_testRadButton7ActionPerformed

    private void testRadButton8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testRadButton8ActionPerformed
    {//GEN-HEADEREND:event_testRadButton8ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_testRadButton8ActionPerformed

    private void testRadButton9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testRadButton9ActionPerformed
    {//GEN-HEADEREND:event_testRadButton9ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_testRadButton9ActionPerformed

    private void testRadButton10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testRadButton10ActionPerformed
    {//GEN-HEADEREND:event_testRadButton10ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_testRadButton10ActionPerformed

    private void catRadBtn1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catRadBtn1ActionPerformed
    {//GEN-HEADEREND:event_catRadBtn1ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_catRadBtn1ActionPerformed

    private void catRadBtn2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catRadBtn2ActionPerformed
    {//GEN-HEADEREND:event_catRadBtn2ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_catRadBtn2ActionPerformed

    private void catRadBtn3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catRadBtn3ActionPerformed
    {//GEN-HEADEREND:event_catRadBtn3ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_catRadBtn3ActionPerformed

    private void catRadBtn5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catRadBtn5ActionPerformed
    {//GEN-HEADEREND:event_catRadBtn5ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_catRadBtn5ActionPerformed

    private void catRadBtn4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catRadBtn4ActionPerformed
    {//GEN-HEADEREND:event_catRadBtn4ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_catRadBtn4ActionPerformed

    private void catRadBtn9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catRadBtn9ActionPerformed
    {//GEN-HEADEREND:event_catRadBtn9ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_catRadBtn9ActionPerformed

    private void catRadBtn6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catRadBtn6ActionPerformed
    {//GEN-HEADEREND:event_catRadBtn6ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_catRadBtn6ActionPerformed

    private void catRadBtn7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catRadBtn7ActionPerformed
    {//GEN-HEADEREND:event_catRadBtn7ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_catRadBtn7ActionPerformed

    private void catRadBtn8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catRadBtn8ActionPerformed
    {//GEN-HEADEREND:event_catRadBtn8ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_catRadBtn8ActionPerformed

    private void catRadBtn10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_catRadBtn10ActionPerformed
    {//GEN-HEADEREND:event_catRadBtn10ActionPerformed
        updateUI(2);
    }//GEN-LAST:event_catRadBtn10ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton catRadBtn1;
    private javax.swing.JRadioButton catRadBtn10;
    private javax.swing.JRadioButton catRadBtn2;
    private javax.swing.JRadioButton catRadBtn3;
    private javax.swing.JRadioButton catRadBtn4;
    private javax.swing.JRadioButton catRadBtn5;
    private javax.swing.JRadioButton catRadBtn6;
    private javax.swing.JRadioButton catRadBtn7;
    private javax.swing.JRadioButton catRadBtn8;
    private javax.swing.JRadioButton catRadBtn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton numBases100000Btn;
    private javax.swing.JRadioButton numBases10000Btn;
    private javax.swing.JRadioButton numBases1000Btn;
    private javax.swing.JRadioButton numBases100Btn;
    private javax.swing.JRadioButton numBases10Btn;
    private javax.swing.JTable resultsTable;
    private javax.swing.JTextArea resultsTextArea;
    private javax.swing.JTextField sigLev1;
    private javax.swing.JTextField sigLev10;
    private javax.swing.JTextField sigLev2;
    private javax.swing.JTextField sigLev3;
    private javax.swing.JTextField sigLev4;
    private javax.swing.JTextField sigLev5;
    private javax.swing.JTextField sigLev6;
    private javax.swing.JTextField sigLev7;
    private javax.swing.JTextField sigLev8;
    private javax.swing.JTextField sigLev9;
    private javax.swing.JCheckBox testLab1;
    private javax.swing.JCheckBox testLab10;
    private javax.swing.JCheckBox testLab2;
    private javax.swing.JCheckBox testLab3;
    private javax.swing.JCheckBox testLab4;
    private javax.swing.JCheckBox testLab5;
    private javax.swing.JCheckBox testLab6;
    private javax.swing.JCheckBox testLab7;
    private javax.swing.JCheckBox testLab8;
    private javax.swing.JCheckBox testLab9;
    private javax.swing.JRadioButton testRadButton1;
    private javax.swing.JRadioButton testRadButton10;
    private javax.swing.JRadioButton testRadButton2;
    private javax.swing.JRadioButton testRadButton3;
    private javax.swing.JRadioButton testRadButton4;
    private javax.swing.JRadioButton testRadButton5;
    private javax.swing.JRadioButton testRadButton6;
    private javax.swing.JRadioButton testRadButton7;
    private javax.swing.JRadioButton testRadButton8;
    private javax.swing.JRadioButton testRadButton9;
    // End of variables declaration//GEN-END:variables

    /**
     * Here we go through the model and make sure that the GUI is looking like what it should
     */
    private void updateUI(int type)
    {
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        ArrayList<String> catnames = model.getTests().get(0).getCatNames();
        if (type == 1)
        {
            String resultsText = "";
            int basepairs = 0;
            if (this.numBases10Btn.isSelected())
            {
                basepairs = 10;
            }
            else if (this.numBases100Btn.isSelected())
            {
                basepairs = 100;
            }
            else if (this.numBases1000Btn.isSelected())
            {
                basepairs = 1000;
            }
            else if (this.numBases10000Btn.isSelected())
            {
                basepairs = 10000;
            }
            else if (this.numBases100000Btn.isSelected())
            {
                basepairs = 100000;
            }
            for (int i = 0; i < model.getTests().size() && i < 10; i++)
            {
                if (boxes.get(i).isSelected())
                {
                    Test t = model.getTests().get(i);
                    if (fields.get(i).getText().length() > 0)
                    {
                        try
                        {
                            t.setSigLevel(Double.parseDouble(fields.get(i).getText()));
                        }
                        catch (Exception e)
                        {
                        }
                    }

                    boxes.get(i).setVisible(true);
                    fields.get(i).setVisible(true);
                    buttons.get(i).setVisible(true);

                    fields.get(i).setText(Double.toString(t.getSigLevel()));
                    boxes.get(i).setText(t.getName());

                    resultsText += t.getTestSummary(basepairs);
                }
            }

            for (String s : catnames)
            {
                resultsText += "---------------------------------------------------------------------------------\n";
                resultsText += "---------------------------" + s + "---------------------------\n";
                resultsText += "---------------------------------------------------------------------------------";
                resultsText += "\n";
                ArrayList<Category> cats = new ArrayList<Category>();
                for (int i = 0; i < model.getTests().size() && i < 10; i++)
                {
                    if (boxes.get(i).isSelected())
                    {
                        Test t = model.getTests().get(i);
                        cats.add(t.getCategory(s));
                    }
                }
                resultsText += Category.getSharedSignificantSnps(cats, basepairs, "tests");
            }
            this.resultsTextArea.setText(resultsText);
        }
        else
        {

            for (int i = 0; i < this.cats.size(); i++)
            {
                if (i >= catnames.size())
                {
                    this.cats.get(i).setVisible(false);
                }
                else
                {
                    this.cats.get(i).setVisible(true);
                    this.cats.get(i).setText(catnames.get(i));
                    if (this.cats.get(i).isSelected())
                    {
                        model.setUpTableModel(catnames.get(i));
                        model.fireTableStructureChanged();
                    }
                }
            }


            for (int i = 0; i < model.getTests().size() && i < 10; i++)
            {
                if (buttons.get(i).isSelected())
                {
                    model.setUpTableModel(i);
                    model.fireTableStructureChanged();
                }
            }
        }
        this.repaint();
        setCursor(Cursor.getDefaultCursor());
    }
}
