/*
 * BedImporter.java
 *
 * Created on Dec 26, 2010, 4:08:23 PM
 */

package control.importing;

import control.itempanel.BedItem;
import control.DataAddRemoveHandler;
import control.NewProjectCreator;
import control.itempanel.ThreadingItemFrame;
import datamodel.Project;
import datamodel.Model;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Gets the required information from the user to start a .BED file import process.
 * @author flaviagrosan
 */
public class BedImporter extends java.awt.Dialog
{
    private ThreadingItemFrame form;
    private BedItem item;

    /**
     * Constructor
     * @param parent
     * @param modal
     */
    public BedImporter(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();

        this.setLocation(parent.getLocation());


        ArrayList<Project> temp = Model.getInstance().getProjects();
        for (int i = 0; i < temp.size(); i++)
        {
            this.projectComboBox.addItem(temp.get(i).getName());
        }
        JFileChooser c = new JFileChooser(Model.getInstance().GetLastFilePath());

        int rVal = c.showOpenDialog(parent);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            this.bedTextBox.setText(c.getSelectedFile().getAbsolutePath());
            this.nameField.setText(removeExtension(c.getSelectedFile().getName()));
            Model.getInstance().AccountForLastFilePath(c.getSelectedFile().getAbsolutePath());
        }
    }

    private String removeExtension(String s)
    {
        int idx = s.indexOf('.');
        if (idx > 0)
        {
            return s.substring(0, idx);
        }
        return s;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bimTextBox = new javax.swing.JTextField();
        famTextBox = new javax.swing.JTextField();
        projectComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bedButton = new javax.swing.JButton();
        bimButton = new javax.swing.JButton();
        famButton = new javax.swing.JButton();
        bedHelpButton = new javax.swing.JButton();
        bimHelpButton = new javax.swing.JButton();
        famHelpButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bedTextBox = new javax.swing.JTextField();
        markerName = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        importButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        jLabel4.setText("BED/BIM Import");

        bimTextBox.setEditable(false);
        bimTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bimTextBoxMouseClicked(evt);
            }
        });

        famTextBox.setEditable(false);
        famTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                famTextBoxMouseClicked(evt);
            }
        });

        projectComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select Project>", "Create New Project" }));

        jLabel5.setText("Project");

        jLabel6.setText("BED file:");

        bedButton.setText("...");
        bedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedButtonActionPerformed(evt);
            }
        });

        bimButton.setText("...");
        bimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimButtonActionPerformed(evt);
            }
        });

        famButton.setText("...");
        famButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                famButtonActionPerformed(evt);
            }
        });

        bedHelpButton.setText("?");
        bedHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedHelpButtonActionPerformed(evt);
            }
        });

        bimHelpButton.setText("?");
        bimHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimHelpButtonActionPerformed(evt);
            }
        });

        famHelpButton.setText("?");
        famHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                famHelpButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("BIM file:");

        jLabel8.setText("FAM file:");

        bedTextBox.setEditable(false);
        bedTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bedTextBoxMouseClicked(evt);
            }
        });

        jLabel9.setText("Dataset name:");

        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("                           ");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(markerName)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(jLabel5)
                                .add(31, 31, 31)
                                .add(projectComboBox, 0, 317, Short.MAX_VALUE)
                                .add(174, 174, 174))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel7)
                                    .add(jLabel6)
                                    .add(jLabel8)
                                    .add(jLabel9))
                                .add(4, 4, 4)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(famTextBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, bimTextBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, nameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, bedTextBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(famButton)
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                        .add(bedButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(bimButton)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, bimHelpButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .add(famHelpButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, bedHelpButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(importButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(136, 136, 136)
                                .add(errorLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 262, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(markerName)
                        .add(135, 135, 135))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel4)
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5)
                            .add(projectComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(nameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel9))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(bedTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6)
                            .add(bedHelpButton)
                            .add(bedButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(bimTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(bimHelpButton)
                            .add(bimButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel8)
                            .add(famTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(famButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(famHelpButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(63, 63, 63)
                        .add(errorLabel))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(importButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(67, 67, 67))
        );

        add(jPanel1, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void bimTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bimTextBoxMouseClicked
        bimButtonActionPerformed(null);
}//GEN-LAST:event_bimTextBoxMouseClicked

    private void famTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_famTextBoxMouseClicked
        famButtonActionPerformed(null);
}//GEN-LAST:event_famTextBoxMouseClicked

    private void bedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedButtonActionPerformed
        JFileChooser c = new JFileChooser(Model.getInstance().GetLastFilePath());
        // Demonstrate "Open" dialog:
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            this.bedTextBox.setText(c.getSelectedFile().getAbsolutePath());
            Model.getInstance().AccountForLastFilePath(c.getSelectedFile().getAbsolutePath());
        }
}//GEN-LAST:event_bedButtonActionPerformed

    private void bimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimButtonActionPerformed
        JFileChooser c = new JFileChooser(Model.getInstance().GetLastFilePath());
        // Demonstrate "Open" dialog:
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            this.bimTextBox.setText(c.getSelectedFile().getAbsolutePath());
            Model.getInstance().AccountForLastFilePath(c.getSelectedFile().getAbsolutePath());
        }
}//GEN-LAST:event_bimButtonActionPerformed

    private void famButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_famButtonActionPerformed
        JFileChooser c = new JFileChooser(Model.getInstance().GetLastFilePath());
        // Demonstrate "Open" dialog:
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            this.famTextBox.setText(c.getSelectedFile().getAbsolutePath());
            Model.getInstance().AccountForLastFilePath(c.getSelectedFile().getAbsolutePath());
        }
}//GEN-LAST:event_famButtonActionPerformed

    private void bedHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedHelpButtonActionPerformed
        String s = "Select the file that contains the marker values in binary format";
        JOptionPane.showMessageDialog(this, s, "Help", JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_bedHelpButtonActionPerformed

    private void bimHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimHelpButtonActionPerformed
        String s = "Select a file with marker labels";
        JOptionPane.showMessageDialog(this, s, "Help", JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_bimHelpButtonActionPerformed

    private void famHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_famHelpButtonActionPerformed
        String s = "Select the file with sample information";
        JOptionPane.showMessageDialog(this, s, "Help", JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_famHelpButtonActionPerformed

    private void bedTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bedTextBoxMouseClicked
        bedButtonActionPerformed(null);
}//GEN-LAST:event_bedTextBoxMouseClicked

    /**
     * Calls to import the .BED file after a few checks.
     * @param evt
     */
    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        if (this.projectComboBox.getSelectedItem().equals("<Select Project>"))
        {
            String s = "You must select a valid project option.";
            //JOptionPane.showMessageDialog(this, s, "Input Error", JOptionPane.ERROR_MESSAGE);
            this.errorLabel.setText(s);
            return;
        }


        if (this.nameField.getText().equals(""))
        {
            String s = "You must select a valid name.";
            //JOptionPane.showMessageDialog(this, s, "Input Error", JOptionPane.ERROR_MESSAGE);
            this.errorLabel.setText(s);
            return;
        }

        if (this.projectComboBox.getSelectedItem().equals("Create New Project"))
        {
            NewProjectCreator creator = new NewProjectCreator(this, true);
            creator.show();

            if (creator.SUCCESS)
            {
                this.projectComboBox.addItem(creator.newProjectName);
                this.projectComboBox.setSelectedItem(creator.newProjectName);
                DataAddRemoveHandler.getInstance().addProject(creator.newProjectName);
                DataAddRemoveHandler.getInstance().refreshDisplay();
            }
            else
            {
                this.errorLabel.setText("Adding the new project failed.");
                return;
            }
        }

        if (Model.getInstance().getProject(projectComboBox.getSelectedItem().toString()).getMarker(this.nameField.getText()) != null)
        {
            this.errorLabel.setText("This marker set already exists in this project");
            return;
        }

        File ped = new File(this.bedTextBox.getText());
        if (!ped.exists())
        {
            this.errorLabel.setText("BED file does not exist.");
            return;
        }

        File map = new File(this.bimTextBox.getText());
        if (!map.exists())
        {
            this.errorLabel.setText("MAP file does not exist.");
            return;
        }

        File lab = new File(this.famTextBox.getText());
        if (!lab.exists() && this.jLabel7.isEnabled())
        {
            this.errorLabel.setText("Label file does not exist.");
            return;
        }

        setVisible(false);
        dispose();

        form = ThreadingItemFrame.getInstance();
        item = new BedItem(form, nameField.getText(),
                Model.getInstance().getProject(this.projectComboBox.getSelectedItem().toString()).getId(),
                ped.getPath(), map.getPath(), lab.getPath());
        form.addToThreadList(item);
        form.setVisible(true);
        form.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_importButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.closeDialog(null);
}//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Set the selected project in the dialog to this project
     * @param project the project to work with.
     */
    public void setSeletedProject(String project)
    {
        for (int i = 0; i < this.projectComboBox.getItemCount(); i++)
        {
            if (this.projectComboBox.getItemAt(i).equals(project))
            {
                this.projectComboBox.setSelectedIndex(i);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bedButton;
    private javax.swing.JButton bedHelpButton;
    private javax.swing.JTextField bedTextBox;
    private javax.swing.JButton bimButton;
    private javax.swing.JButton bimHelpButton;
    private javax.swing.JTextField bimTextBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton famButton;
    private javax.swing.JButton famHelpButton;
    private javax.swing.JTextField famTextBox;
    private javax.swing.JButton importButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel markerName;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox projectComboBox;
    // End of variables declaration//GEN-END:variables
}
