package control.importing;

import control.DataAddRemoveHandler;
import control.itempanel.MarkerItem;
import control.NewProjectCreator;
import control.itempanel.ThreadingItemFrame;
import datamodel.Project;
import datamodel.Model;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 * We will gather the required information to start a marker import through
 * this form. 
 * @author ross
 */
public class MarkerImporter extends java.awt.Dialog
{
    private String fileName = "";
    private JFrame parent;
    private ThreadingItemFrame form;
    private MarkerItem item;

    /**
     * Creates a new MarkerImporter
     * @param parent
     * @param modal
     */
    public MarkerImporter(java.awt.Container parent, boolean modal)
    {
        super((JFrame) parent, modal);
        //super(parent, modal);
        this.parent = (JFrame) parent;

        initComponents();
        this.setLocation(parent.getLocation());

        ArrayList<Project> temp = Model.getInstance().getProjects();
        for (int i = 0; i < temp.size(); i++)
        {
            this.projectComboBox.addItem(temp.get(i).getName());
        }
        JFileChooser c = new JFileChooser(Model.getInstance().GetLastFilePath());

        int rVal = c.showOpenDialog(parent);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            this.markerTextBox.setText(c.getSelectedFile().getAbsolutePath());
            this.nameField.setText(removeExtension(c.getSelectedFile().getName()));
            Model.getInstance().AccountForLastFilePath(c.getSelectedFile().getAbsolutePath());
        }

    }

    /**
     * Removes an extension off of the string passed in. 
     * @param s
     * @return
     */
    private String removeExtension(String s)
    {
        int idx = s.indexOf('.');
        if (idx > 0)
        {
            return s.substring(0, idx);
        }
        return s;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dimButtonGroup = new javax.swing.ButtonGroup();
        headButtonGroup = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        delimiterTextBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sampleTextBox = new javax.swing.JTextField();
        labelTextBox = new javax.swing.JTextField();
        projectComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fileButton = new javax.swing.JButton();
        sampleButton = new javax.swing.JButton();
        labelButton = new javax.swing.JButton();
        fileHelpButton = new javax.swing.JButton();
        sampleHelpButton = new javax.swing.JButton();
        labelHelpButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        markerTextBox = new javax.swing.JTextField();
        markerName = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        isHasDataCkBx = new javax.swing.JCheckBox();
        cancelButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setTitle("Import Data");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));

        jLabel2.setText("delimeter");

        delimiterTextBox.setText("w");
        delimiterTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delimiterTextBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 18));
        jLabel3.setText("Marker Import");

        sampleTextBox.setEditable(false);
        sampleTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sampleTextBoxMouseClicked(evt);
            }
        });

        labelTextBox.setEditable(false);
        labelTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTextBoxMouseClicked(evt);
            }
        });

        projectComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Select Project>", "Create New Project" }));

        jLabel4.setText("Project");

        jLabel5.setText("Marker file:");

        fileButton.setText("...");
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        sampleButton.setText("...");
        sampleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleButtonActionPerformed(evt);
            }
        });

        labelButton.setText("...");
        labelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelButtonActionPerformed(evt);
            }
        });

        fileHelpButton.setText("?");
        fileHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileHelpButtonActionPerformed(evt);
            }
        });

        sampleHelpButton.setText("?");
        sampleHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sampleHelpButtonActionPerformed(evt);
            }
        });

        labelHelpButton.setText("?");
        labelHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelHelpButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Sample Labels:");

        jLabel7.setText("Marker Labels:");

        markerTextBox.setEditable(false);
        markerTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                markerTextBoxMouseClicked(evt);
            }
        });

        jLabel8.setText("Marker name:");

        isHasDataCkBx.setText("Import w/o data");
        isHasDataCkBx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isHasDataCkBxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(projectComboBox, 0, 401, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(markerName)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                    .addComponent(markerTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                    .addComponent(sampleTextBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                    .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(delimiterTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(256, 256, 256)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isHasDataCkBx)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(labelButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                    .addComponent(sampleButton, 0, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sampleHelpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(fileHelpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(labelHelpButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(projectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(markerName)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileHelpButton)
                    .addComponent(fileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markerTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sampleHelpButton)
                    .addComponent(sampleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sampleTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelButton)
                    .addComponent(labelHelpButton)
                    .addComponent(jLabel7)
                    .addComponent(labelTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(delimiterTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isHasDataCkBx))
                .addGap(60, 60, 60))
        );

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("                           ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Marker name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.closeDialog(null);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void fileHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileHelpButtonActionPerformed
        String s = "Select the file that contains the marker values for each sample";
        JOptionPane.showMessageDialog(this, s, "Help", JOptionPane.INFORMATION_MESSAGE);
        openExampleFile("markerExample.txt");
    }//GEN-LAST:event_fileHelpButtonActionPerformed

    private void sampleHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleHelpButtonActionPerformed
        String s = "Select a file with one row for each sample label";
        JOptionPane.showMessageDialog(this, s, "Help", JOptionPane.INFORMATION_MESSAGE);
        openExampleFile("sampleEx.txt");
    }//GEN-LAST:event_sampleHelpButtonActionPerformed

    private void labelHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelHelpButtonActionPerformed
        String s = "Select the file with one row for each marker label (three columns - chr name locus)";
        JOptionPane.showMessageDialog(this, s, "Help", JOptionPane.INFORMATION_MESSAGE);
        openExampleFile("chrLabs.txt");
    }//GEN-LAST:event_labelHelpButtonActionPerformed

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        JFileChooser c = new JFileChooser(Model.getInstance().GetLastFilePath());
        // Demonstrate "Open" dialog:
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            this.markerTextBox.setText(c.getSelectedFile().getAbsolutePath());
            Model.getInstance().AccountForLastFilePath(c.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_fileButtonActionPerformed

    private void sampleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sampleButtonActionPerformed
        JFileChooser c = new JFileChooser(Model.getInstance().GetLastFilePath());
        // Demonstrate "Open" dialog:
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            this.sampleTextBox.setText(c.getSelectedFile().getAbsolutePath());
            Model.getInstance().AccountForLastFilePath(c.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_sampleButtonActionPerformed

    private void labelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelButtonActionPerformed
        JFileChooser c = new JFileChooser(Model.getInstance().GetLastFilePath());
        // Demonstrate "Open" dialog:
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            this.labelTextBox.setText(c.getSelectedFile().getAbsolutePath());
            Model.getInstance().AccountForLastFilePath(c.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_labelButtonActionPerformed

    private void sampleTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sampleTextBoxMouseClicked
        sampleButtonActionPerformed(null);
    }//GEN-LAST:event_sampleTextBoxMouseClicked

    private void labelTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTextBoxMouseClicked
        labelButtonActionPerformed(null);
    }//GEN-LAST:event_labelTextBoxMouseClicked

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        if (this.projectComboBox.getSelectedItem().equals("<Select Project>"))
        {
            String s = "You must select a valid project option.";
            //JOptionPane.showMessageDialog(this, s, "Input Error", JOptionPane.ERROR_MESSAGE);
            this.errorLabel.setText(s);
            return;
        }

        if (this.delimiterTextBox.getText().equals(""))
        {
            String s = "You must select a valid column delimeter.";
            //JOptionPane.showMessageDialog(this, s, "Input Error", JOptionPane.ERROR_MESSAGE);
            this.errorLabel.setText(s);
            return;
        }
        if (this.nameField.getText().equals(""))
        {
            String s = "You must select a valid Marker name.";
            //JOptionPane.showMessageDialog(this, s, "Input Error", JOptionPane.ERROR_MESSAGE);
            this.errorLabel.setText(s);
            return;


        }

        if (this.projectComboBox.getSelectedItem().equals("Create New Project"))
        {
            NewProjectCreator creator = new NewProjectCreator(this, true);
            creator.show();

            if (creator.SUCCESS)
            {
                this.projectComboBox.addItem(creator.newProjectName);
                this.projectComboBox.setSelectedItem(creator.newProjectName);
                DataAddRemoveHandler.getInstance().addProject(creator.newProjectName);
                DataAddRemoveHandler.getInstance().refreshDisplay();
            }
            else
            {
                this.errorLabel.setText("Adding the new project failed.");
                return;
            }
        }

        if (Model.getInstance().getProject(projectComboBox.getSelectedItem().toString()).getMarker(this.nameField.getText()) != null)
        {
            this.errorLabel.setText("This marker set already exists in this project");
            return;
        }

        File marker = new File(this.markerTextBox.getText());
        if (!marker.exists() && !this.isHasDataCkBx.isSelected())
        {
            this.errorLabel.setText("Marker file does not exist.");
            return;
        }
        File lab = new File(this.labelTextBox.getText());
        if (!lab.exists())
        {
            this.errorLabel.setText("Marker label file does not exist.");
            return;
        }
        String sampfile = this.sampleTextBox.getText();
        if (sampfile.equals(""))
        {
            sampfile = null;
        }
        else
        {
            File samp = new File(sampfile);
            if (!samp.exists())
            {
                this.errorLabel.setText("Sample file does not exist!");
                return;
            }
        }

        setVisible(false);
        dispose();

        String myMarkerTextBoxText = this.markerTextBox.getText();
        if(this.isHasDataCkBx.isSelected())
        {
            myMarkerTextBoxText = null;
        }

        form = ThreadingItemFrame.getInstance();
        item = new MarkerItem(form, nameField.getText(), this.projectComboBox.getSelectedItem().toString(),
                sampfile, labelTextBox.getText(), myMarkerTextBoxText);
        form.addToThreadList(item);
        form.setVisible(true);
        form.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_importButtonActionPerformed

    private void delimiterTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delimiterTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delimiterTextBoxActionPerformed

    private void markerTextBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markerTextBoxMouseClicked
        fileButtonActionPerformed(null);
}//GEN-LAST:event_markerTextBoxMouseClicked

    private void isHasDataCkBxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_isHasDataCkBxActionPerformed
    {//GEN-HEADEREND:event_isHasDataCkBxActionPerformed
        if (this.isHasDataCkBx.isSelected())
        {
            this.jLabel5.setEnabled(false);
            this.jLabel6.setEnabled(false);
            this.fileButton.setEnabled(false);
            this.markerTextBox.setEnabled(false);
            this.fileHelpButton.setEnabled(false);
            this.sampleButton.setEnabled(false);
            this.sampleHelpButton.setEnabled(false);
            this.sampleTextBox.setEnabled(false);
        }
        else
        {
            this.jLabel5.setEnabled(true);
            this.jLabel6.setEnabled(true);
            this.fileButton.setEnabled(true);
            this.markerTextBox.setEnabled(true);
            this.fileHelpButton.setEnabled(true);
            this.sampleButton.setEnabled(true);
            this.sampleHelpButton.setEnabled(true);
            this.sampleTextBox.setEnabled(true);
        }
    }//GEN-LAST:event_isHasDataCkBxActionPerformed

    /**
     * Sets the project that will be defaulted to in the marker import.
     * @param project
     */
    public void setSeletedProject(String project)
    {
        for (int i = 0; i < this.projectComboBox.getItemCount(); i++)
        {
            if (this.projectComboBox.getItemAt(i).equals(project))
            {
                this.projectComboBox.setSelectedIndex(i);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField delimiterTextBox;
    private javax.swing.ButtonGroup dimButtonGroup;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton fileButton;
    private javax.swing.JButton fileHelpButton;
    private javax.swing.ButtonGroup headButtonGroup;
    private javax.swing.JButton importButton;
    private javax.swing.JCheckBox isHasDataCkBx;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton labelButton;
    private javax.swing.JButton labelHelpButton;
    private javax.swing.JTextField labelTextBox;
    private javax.swing.JLabel markerName;
    private javax.swing.JTextField markerTextBox;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox projectComboBox;
    private javax.swing.JButton sampleButton;
    private javax.swing.JButton sampleHelpButton;
    private javax.swing.JTextField sampleTextBox;
    // End of variables declaration//GEN-END:variables

    private void openExampleFile(String filename)
    {
        //Open file in notepad or vi or show error message telling the user where to find the file
        Runtime load = Runtime.getRuntime();
        try
        {
            load.exec("notepad " + filename);
        }
        catch (IOException ex)
        {
            try
            {
                load.exec("vi " + filename);
            }
            catch (IOException ex1)
            {
                JOptionPane.showMessageDialog(this, "I can't open the example file.\n" +
                        "Please look in the distribution directory for " + filename);
            }
        }
    }
}
